### PR TITLE
Revert "Update style.css"

### PR DESCRIPTION
**Pull request by roman-koshchei**
Reverts roman-koshchei/lumin#1

### CODE REVIEW

**Comment by roman-koshchei** [comment]
@roman-koshchei

**Comment by roman-koshchei** [comment]
> @roman-koshchei

csrtr

**Comment by roman-koshchei** [comment]
@roman-koshchei

**Comment by koshcher** [comment]
@roman-koshchei

**Comment by roman-koshchei** [comment]
@roman-koshchei

**Comment by koshcher** [comment]
NEW UPDATE
We made email sending with GitHub

@roman-koshchei

**Pull request merged**
